version: "3.9"

services:
  recoai:
    build: .
    container_name: recoai-server
    ports:
      - "8000:8000"
    volumes:
      - app-data:/app/data/generated
      - app-db:/app/app.db
      - app-models:/app/models
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  app-data:
  app-db:
  app-models:
